import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";

const AppFont = Quicksand({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AI Video Generator App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={AppFont.className}>
        {children}
      </body>
    </html>
  );
}